version: '1.0'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000" 
    environment:
      - PGHOST=database
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=${PGPORT}
      
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - RESET_SECRET=${RESET_SECRET}
      - NODE_ENV=${NODE_ENV}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - FRONTEND_ORIGIN=${FRONTEND_ORIGIN}
    depends_on:
      - database
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - backend-network

  database:
    image: postgres:14
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5432:5432" 
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend-network

volumes:
  db_data:

networks:
  backend-network:
